### ISSUE TITLE
Can u make this compatible for Cent OS

### ISSUE THREAD

**Issue by fayizan** [systemroot/ogar-unlimited-autoinstall#2]
Really awesome work @systemroot , could you please make this compatible with cent os

**Comment by systemroot** [comment]
Follow this Tutorial, 
https://github.com/systemroot/ogar-unlimited-autoinstall/tree/master/CentOS
After some minutes i will update client autoinstaller on centos, 
This is for CentOS 7, Because my provider have only this version off CentOS, :confused: 
*But you can try even if is an older i think this will work without any problem!*
